[build]
  publish = "frontend/build"   # Путь к статическим файлам фронтенда
  functions = "functions"      # Путь к backend-функциям

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200